feat(auditing): disables typo tolerance
metal-stack/metal-lib pull request #148
Opened 2024-07-30 08:45 UTC by vknabel

meilisearch-go v0.27.1 fixes an issue where the typo tolerance could not be disabled. This should reduce the complexity of indexes but requires a settings migration period for every index.

https://github.com/meilisearch/meilisearch-go/releases/tag/v0.27.1

2024-07-31 05:38 UTC, majst01 commented
should be tested with existing data

2024-08-02 13:39 UTC, vknabel commented
works as expected

2024-08-08 07:15 UTC, majst01 requested changes

2024-08-08 07:15 UTC, majst01 commented on go.mod
> +	github.com/meilisearch/meilisearch-go v0.27.1
```suggestion
	github.com/meilisearch/meilisearch-go v0.27.2
```

2024-08-08 08:16 UTC, majst01 approved these changes

2024-08-08 08:21 UTC, merged